version: '3.1'
services:
  postgres:
    image: postgres:13.6
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data
    container_name: postgres-db
    volumes:
      - ./pg-scripts:/docker-entrypoint-initdb.d